### ISSUE TITLE
tabular data browser

### ISSUE THREAD

**Issue by mcfrank** [langcog/irw_site#4]
we are hoping to have this as a plugin from redivis

**Comment by imathews** [comment]
Definitely doable on our end. I think the first step is to define what this should look like. 

Right now the table module on Redivis ([example](https://redivis.com/datasets/7br5-41440fjzk/tables/6fff-7hqb797cb#cells)) is made up of three tabs:
- Variables: a list of variables
- Cells: A grid view
- Query: A place to run quick SQL queries and view results. A technical constraint here is that the viewer would need to be logged in to Redivis to run a query, since queries are always tied to a user.

@mcfrank @mikabr, what are your thoughts on these different tabs, vs. maybe a simplified view? Or more generally, what sort of content would be most useful to see here?

**Comment by imathews** [comment]
I guess to clarify — do we want an embeddable table module (linked above), or some way to embed the list of all tables on a dataset, similar to the "Tables" tab on the dataset page?

**Comment by mcfrank** [comment]
Hi Ian, thanks for checking in! I think there are maybe two use case. 

The first would be to embed a single table. This would be a simplified Table module, where you could see the variables and the cells. I think instead of a query tab, you might consider just an "open in redivis" button or nothing at all. 

The second would be to embed all the tables, like the Tables tab. Being able to drill down from this would be cool. That way you'd essentially be building in a public browser of the dataset - someone could get a really god sense of what was there quite easily. 

But I don't have a sense of how hard this is...

**Comment by mcfrank** [comment]
Thanks so much for following up. I like the way those look. I think that
would be more than sufficient for our purposes, at least for a table
viewer.

Design-wise, keeping the redivis look and feel is good, though I do
wonder if it's going to feel very plug-in like to have a gray box. Maybe
that's unavoidable? I don't know enough about the technical issues to know
whether it's even an option to inherit style from the underlying page.
Maybe 2.0?

**Comment by imathews** [comment]
Thanks @mcfrank! I don't think inherited styles within an iframe are really doable (from a tech perspective), but I could see the utility of being able to customize a few parameters for the embed (also primary color, which is currently the "redivis purple"). Agree that saving this for a 2.0 makes sense, in the interest of getting something out.

Do you have a sense of a rough timeline for when you'd want to get this out? Just so that we can line up our work accordingly... this shouldn't take too much time, but we're just balancing various priorities on our end.

**Comment by mcfrank** [comment]
Makes total sense about inheritance.

We have one site that we're working on and maybe would like to deploy in
the next few weeks or so. That's our minimal proof of concept site for IRW
that I linked in the slack. v1.0 is more than fine for that!
